name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
    - uses: actions/checkout@master
    - name: download htslib
      run: |
        wget https://github.com/samtools/htslib/releases/download/1.12/htslib-1.12.tar.bz2
        sudo apt-get install gcc-11
    - name: untar
      run: tar xf htslib-1.12.tar.bz2
    - name: install htslib
      env:
        CC: gcc-11
      run: |
        cd htslib-1.12/
        autoreconf -i
        ./configure
        make
        sudo make install
    - name: autotools
      env:
        CC: gcc-11
      run: ./autogen.sh
    - name: configure
      env:
        CC: gcc-11
      run: ./configure
    - name: make
      env:
        CC: gcc-11
      run: make
    - name: make check
      env:
        CC: gcc-11
      run: make check
    - name: make install
      env:
        CC: gcc-11
      run: sudo make install

  build-macos:

    runs-on: [ macos-14 ]

    steps:
    - uses: actions/checkout@master
    - name: install GNU autotools
      run: |
        brew install autoconf automake libtool
    - name: download htslib
      run: wget https://github.com/samtools/htslib/releases/download/1.12/htslib-1.12.tar.bz2
    - name: untar
      run: tar xf htslib-1.12.tar.bz2
    - name: install htslib
      run: |
        cd htslib-1.12/
        autoreconf -i
        ./configure
        make
        sudo make install
    - name: autoconf
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make install
      run: sudo make install
